trigger:
  branches:
    include:
      - master
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      # ref: refs/tags/v0.12.0
      endpoint: github

variables:
  Configuration: Release
  Verbosity: Normal
  Coverage: "$(Agent.BuildDirectory)/c"
  VstsCoverage: "$(Coverage)"
  Artifacts: $(Build.ArtifactStagingDirectory)
  VstsArtifacts: "$(Artifacts)"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"

jobs:
  - template: pipeline/cake.yml@rsg
    parameters:
      dependsOn: GitVersion
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      Script: build.cake
      EnableReleaseNotes: false
      Matrix:
        Windows:
          BuildName: "Windows"
          ImageName: "windows-latest"
        Linux:
          BuildName: "Linux"
          ImageName: "ubuntu-latest"
